### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by duylethanh**
This PR contains documentation for instances in the `experiments.yml`.

### CODE REVIEW

**Comment by avdgrinten** [comment]
Thanks for the PR. The text looks good but I'm not sure if the experiment.yml reference page is the best location for it. I'd like to see a reference of the experiments.yml file sorted by keys/blocks.

We should still keep the text that you wrote, just move it somewhere else. Possibly to an own "Instances" page. We could rename the `Usage Guide` to `Quick Start` or something similar to reflect this.

**Comment by duylethanh** [comment]
> I'd like to see a reference of the experiments.yml file sorted by keys/blocks.

Is it not already (see image below) or do you mean something else?

image


> We could rename the `Usage Guide` to `Quick Start` or something similar to reflect this.

This sounds like a good idea.

**Comment by duylethanh** [comment]
I updated the PR. I moved the text to an own Instance page and made slight changes to it. I also added a reference for the keys used for instances in the `experiments.yml` and renamed `Usage Guide` to `Quick Start`.

**Comment by avdgrinten** [comment]
Thank you for the PR! Merging...

**Pull request merged**
